language: ruby
rvm:
- 2.1.2

addons:
    postgresql: "9.3"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - xvfb-run --server-args="-screen 99.0 1024x768x24" bundle exec rspec spec/features/*.rb
deploy:
  provider: heroku
  app: kalevankierros
  api_key:
    secure: Ev466/UZStDK64HTI8K1b2NZV3pxCCI5DKXbm1VKNSPLwX7BCvc4vPffB667hsBSfPSub3wCbApLTV55BR3PbUmwF6M1zAx2XqJ6qrSOI/MaWLWKOfDwrqTENYgtXm1IiK0Hm0+gtXOXVfhhdQAI1hCwip9GWkk+YAO2oZCxUE4=

notifications:
  email:
    on_success: never
    on_failure: always
