language: ruby
rvm:
- 2.1.2

addons:
    postgresql: "9.3"
before_install:
  - "export DISPLAY=99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake minitest:features
deploy:
  provider: heroku
  app: kalevankierros
  api_key:
    secure: Ev466/UZStDK64HTI8K1b2NZV3pxCCI5DKXbm1VKNSPLwX7BCvc4vPffB667hsBSfPSub3wCbApLTV55BR3PbUmwF6M1zAx2XqJ6qrSOI/MaWLWKOfDwrqTENYgtXm1IiK0Hm0+gtXOXVfhhdQAI1hCwip9GWkk+YAO2oZCxUE4=

notifications:
  email:
    on_success: never
    on_failure: always
