development:
  address: smtp.gmail.com
  port: 587
  domain: gmail.com
  user_name: ENV['EMAIL_ADDRESS'] || raise('ERROR Set E-MAIL ADDRESS in config/email.yml')
  password: ENV['EMAIL_PASSWORD'] || raise('ERROR Set E-MAIL PASSWORD in config/email.yml')
  authentication: plain
  enable_starttls_auto: true
test:
  user_name: test@test.com
production:
  address: smtp.gmail.com
  port: 587
  domain: gmail.com
  user_name: ENV['EMAIL_ADDRESS'] || raise('ERROR Set E-MAIL ADDRESS in config/email.yml')
  password: ENV['EMAIL_PASSWORD'] || raise('ERROR Set E-MAIL PASSWORD in config/email.yml')
  authentication: plain
  enable_starttls_auto: true
